# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('S', 'Subjective'), ('O', 'Objective'), ('C', 'Checkbox'), ('G', 'Grades'), ('A', 'Appointment')], default='S', max_length=1),
        ),
    ]
