# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0004_auto_20170517_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktype',
            name='name',
            field=models.CharField(choices=[('prev_results', 'Results'), ('appointment', 'Appointment'), ('review', 'Take a Review'), ('future_courses', 'Available courses')], max_length=48, unique=True),
        ),
    ]
