# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0006_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_manager.Appointment'),
        ),
    ]
