# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0008_auto_20170518_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
