# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0010_auto_20170518_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
