# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0011_auto_20170518_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='Time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_manager.TimeTable'),
        ),
    ]
