# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0013_auto_20170518_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='Time_table',
            new_name='time_table',
        ),
    ]
